Revert "integration_tests/supervisor: Add example for mock server router based by URLPattern"
This reverts commit 0342f5bfd48720dbf0d467c8fd62ffb66d9b3b49 due to CI
failures:

```
file:////fastly-compute-template/integration_tests/pkgs/mock_server/src/shared/mini_url_pattern_router.js:43
        const pattern = new URLPattern(pat);
                        ^

TypeError: Failed to construct URLPattern
    at file:///fastly-compute-template/integration_tests/pkgs/mock_server/src/shared/mini_url_pattern_router.js:43:25
    at Array.map (<anonymous>)
    at buildMatcherFromURLPattern (file:////integration_tests/pkgs/mock_server/src/shared/mini_url_pattern_router.js:42:38)
    at file:////integration_tests/pkgs/mock_server/src/main.js:9:17
    at ModuleJob.run (node:internal/modules/esm/module_job:365:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:665:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:99:5) {
  code: 'ERR_INVALID_URL_PATTERN'
}
```